config/routes.rb
Lucidword::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    member do
      post :follow
      post :unfollow
    end
  end


  resources :beginnings do
    member do
      post :bookmark
      post :unbookmark
    end
  end
 
  resources :endings do
    member do 
      post :praise
      post :unpraise
      post :bookmark
      post :unbookmark
      post :publish
      post :unpublish
    end
  end

  resources :comments

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
# Include default devise modules. Others available are:
# :token_authenticatable, :confirmable,
# :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  acts_as_voter
  acts_as_voteable
  acts_as_followable
  acts_as_follower

  has_many :beginnings  
  has_many :endings
  has_many :comments
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def  follow
    begin
      current_user.follow(@user = User.find(params[:id]))

      respond_to do |format|
        format.html { redirect_to @user, notice: 'You are now following this author' }
        format.js
      end
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def unfollow
    begin
      current_user.stop_following(@user = User.find(params[:id]))

      respond_to do |format|
        format.html { redirect_to current_user, notice: 'You have stopped follwing this author' }
         format.js
       end

    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @praise = @user.plusminus
    @endingbookmarks = @user.following_by_type('Ending')
    @beginningbookmarks = @user.following_by_type('Beginning')
    @userfollowed = @user.following_by_type('User')

  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<div class="free-button">
<%= link_to 'Follow this user!', follow_user_path(@user), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/users/_unfollow.html.erb
<div class="free-button">
<%= link_to 'Stop following user', unfollow_user_path(@user), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/users/follow.js.erb
$("#followform").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#follow").html('<%= pluralize(@user.followers_count, ' time') %>')

app/views/users/index.html.erb
<h1>Listing all users</h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
<%= gravatar_image_tag( user.email, :alt => user.name ) %>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<div class="row">
<div class="span4">
<h1><%= @user.name %>'s Profile</h1>
<% if current_user != @user %>
<div id="followform">
<% if @user.followed_by?(current_user) %>
<%= render 'unfollow' %>
<% else %>
<%= render 'follow' %>
<% end %>
</div>
<% end %>
<br />

<%= gravatar_image_tag( @user.email, :alt => @user.name, :gravatar => { :size => 80 }) %>

<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p><%= @user.name %> has written <%= pluralize( @user.beginnings.count, 'beginning') %>.</p>
<p><%= @user.name %> has written <%= pluralize( @user.endings.count, 'ending') %>.</p>
<p><%= @user.name %>'s writing has been praised <%= pluralize(@praise, ' time') %>.</p>
<p><%= @user.name %> has bookmarked <%= pluralize(@user.following_endings_count, ' ending') %>.</p>
<p><%= @user.name %> has bookmarked <%= pluralize(@user.following_beginnings_count, ' beginning') %>.</p>
<p><%= @user.name %> has been followed <strong id="follow" style="font-weight: normal"><%= pluralize(@user.followers_count, ' time') %></strong>.</p>
<p><%= @user.name %> is following <%= pluralize(@user.following_by_type_count('User'), 'user') %>.</p>
</div>
</div>
<!--<h2>User following system</h2>
<div id="followform">
<p>
<% if @user.followed_by?(current_user) %>
<%= render 'unfollow' %>
<% else %>
<%= render 'follow' %>
<% end %>
</p>
</div>
-->
<p>
  <h2>Users <%= @user.name %> is following </h2>
</p>
<div class="row">
<div class="span4">
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Controls</th>
  </tr>
<% @userfollowed.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user_path(user), :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Unfollow', unfollow_user_path(user), method: :post, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
  </tr>
<% end %>
</table>
</div>
</div>
<br />
<div class ="row">
<div class="span4">
<p>
  <h2><%= @user.name %>'s Bookmarked Endings </h2>
</p>

<table class="table table-striped">
  <tr>
    <th>Ending Title</th>
    <th>Ending Author</th>
    <th>What Beginning?</th>
    <th>Controls</th>
  </tr>
<% @endingbookmarks.each do |bookmark| %>
  <tr>
    <td><%= bookmark.title %></td>
    <td><%= bookmark.user.name %></td>
    <td><%= bookmark.beginning.title %></td>
    <td><%= link_to 'Unbookmark', unbookmark_ending_path(bookmark), method: :post, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
  </tr>
<% end %>
</table>
</div>
</div>

<div class ="row">
<div class ="span4">
<p>
  <h2><%= @user.name %>'s Bookmarked Beginnings </h2>
</p>
<table class="table table-striped">
  <tr>
    <th>Beginning Title</th>
    <th>Beginning Author</th>
    <th>Controls</th>

  </tr>

<% @beginningbookmarks.each do |bookmark| %>
  <tr>
    <td><%= bookmark.title %></td>
    <td><%= bookmark.original_author %></td>

      <td><%= link_to 'Unbookmark', unbookmark_beginning_path(bookmark), method: :post, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
  </tr>
<% end %>
</table>
</div>
</div>

<div class="row">
<div class="span6">
<p>
  <h2><%= @user.name %>'s Endings </h2>
</p>
<table class="table table-striped">
  <tr>
    <th>What beginning</th>
    <th>Title</th>
    <th>Created</th>
    <th>Controls</th>
  </tr>

<% @user.endings.each do |ending| %>
  <tr>
    <td><%= ending.beginning.title %></td>
    <td><%= ending.title %></td>
    <td><%= time_ago_in_words(ending.created_at) %> ago</td>
    <td><%= link_to 'Show', ending, :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_ending_path(ending), :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Destroy', ending, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
  </tr>
<% end %>
</table>
</div>
</div>

<div class="row">
<div class="span6">
<p>
  <h2><%= @user.name %>'s Beginnings </h2>
</p>
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Original Author</th>
    <th>Created</th>
    <th>Controls</th>

  </tr>

<% @user.beginnings.each do |beginning| %>
  <tr>
    <td><%= beginning.title %></td>
    <td><%= beginning.original_author %></td>
    <td><%= time_ago_in_words(beginning.created_at) %> ago</td>
    <td><%= link_to 'Show', beginning, :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_beginning_path(beginning), :class => 'btn btn-primary' %></td>
    <td><%= link_to 'Destroy', beginning, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
  </tr>
<% end %>
</table>
</div>
</div>

app/views/users/unfollow.js.erb
$("#followform").html("<%= escape_javascript(render('users/follow')) %>")
$("#follow").html('<%= pluralize(@user.followers_count, ' time') %>')