config/routes.rb
Lucidword::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    member do
      post :follow
      post :unfollow
    end
  end


  resources :beginnings do
    member do
      post :bookmark
      post :unbookmark
    end
  end
 
  resources :endings do
    member do 
      post :praise
      post :unpraise
      post :bookmark
      post :unbookmark
      post :publish
      post :unpublish
    end
  end

  resources :comments

end

app/models/ending.rb
class Ending < ActiveRecord::Base

  attr_accessible :beginning_id, :content, :title, :private

  acts_as_voteable
  acts_as_followable

  belongs_to :user
  belongs_to :beginning
  has_many :comments

  validates :content, presence: true
  validates :user_id, presence: true

  default_scope order: 'endings.created_at DESC'

end

app/controllers/endings_controller.rb
class EndingsController < ApplicationController

  before_filter :authenticate_user!

  def  publish
    begin
      @ending = Ending.find(params[:id])
      @ending.toggle!(:private)

      respond_to do |format|
        format.html { redirect_to @ending, notice: 'Ending made public' }
        format.js
      end
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def unpublish
    begin
      @ending = Ending.find(params[:id])
      @ending.toggle!(:private)

      respond_to do |format|
        format.html { redirect_to @ending, notice: 'Ending made private' }
         format.js
       end

    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def  bookmark
    begin
      current_user.follow(@ending = Ending.find(params[:id]))

      respond_to do |format|
        format.html { redirect_to current_user, notice: 'You have bookmarked this ending' }
        format.js
      end
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def unbookmark
    begin
      current_user.stop_following(@ending = Ending.find(params[:id]))

      respond_to do |format|
        format.html { redirect_to current_user, notice: 'You have removed your bookmark' }
         format.js
       end

    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def praise
    begin
      current_user.vote_exclusively_for(@ending = Ending.find(params[:id]))
      current_user.vote_for(@ending.user)

      respond_to do |format|
        format.html { redirect_to @ending, notice: 'You have praised this ending' }
        format.js
      end
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def unpraise
    begin
      current_user.unvote_for(@ending = Ending.find(params[:id]))
      current_user.vote_against(@ending.user)

      respond_to do |format|
        format.html { redirect_to @ending, notice: 'You have removed your praise for this ending' }
         format.js
       end
 
    
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end



  # GET /endings
  # GET /endings.json
  def index
    @endings = Ending.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @endings }
    end
  end

  # GET /endings/1
  # GET /endings/1.json
  def show
    @ending = Ending.find(params[:id])
    @votes = @ending.votes_for
    @comment = Comment.new(:ending_id => params[:id], :user => current_user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ending }
    end
  end

  # GET /endings/new
  # GET /endings/new.json
  def new
    @ending = Ending.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ending }
    end
  end

  # GET /endings/1/edit
  def edit
    @ending = Ending.find(params[:id])

  end

  # POST /endings
  # POST /endings.json
  def create
    @user = current_user
    @ending = @user.endings.new(params[:ending])

    respond_to do |format|
      if @ending.save
        format.html { redirect_to @ending, notice: 'Ending was successfully created.' }
        format.json { render json: @ending, status: :created, location: @ending }
      else
        format.html { render action: "new" }
        format.json { render json: @ending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /endings/1
  # PUT /endings/1.json
  def update
    @ending = Ending.find(params[:id])

    respond_to do |format|
      if @ending.update_attributes(params[:ending])
        format.html { redirect_to @ending, notice: 'Ending was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endings/1
  # DELETE /endings/1.json
  def destroy
    @ending = Ending.find(params[:id])
    @ending.destroy

    respond_to do |format|
      format.html { redirect_to endings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/endings_helper.rb
module EndingsHelper
end

app/views/endings/_bookmark.html.erb
<div class="bm-form">
<%= link_to 'Bookmark this ending!', bookmark_ending_path(@ending), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/endings/_form.html.erb
<div class="form-inputs">
<%= simple_form_for(@ending) do |f| %>
  <%= f.error_notification %>

<p>
  <b>Beginning Title:</b>
  <%= @ending.beginning.title %>
</p>
<p>
  <b>Beginning Content:</b>
  <%= simple_format (@ending.beginning.content) %>
</p>


  <%= f.input :content, :label => false, :as => :text, :input_html => { :class => "span6" }  %>

<p>
  <b>Want a new title for your ending?</b>
  <%= f.input :title, :label => false, :input_html => { :class => "span4" } %>
</p>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
  </div>

 <div class="form-actions">
<div id="publishform">
<p>
<% if @ending.private? %>
<%= render 'publish' %>
<% else %>
<%= render 'unpublish' %>
<% end %>
</p>
</div>
</div>

<% end %>

app/views/endings/_praise.html.erb
<div class="pr-form">
<%= link_to 'Praise this ending!', praise_ending_path(@ending), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/endings/_unbookmark.html.erb
<div class="bm-form">
<%= link_to 'Remove bookmark', unbookmark_ending_path(@ending), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/endings/_unpraise.html.erb
<div class="pr-form">
<%= link_to 'Unpraise this ending', unpraise_ending_path(@ending), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/endings/_unpublish.html.erb
<div class="pb-form">
<p>This ending is currently public</p>
<%= link_to 'Make ending private', unpublish_ending_path(@ending), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/endings/bookmark.js.erb
$("#bookmarkform").html("<%= escape_javascript(render('endings/unbookmark')) %>")
$("#bookmarked").html('<%= pluralize(@ending.followers_count, ' time') %>')

app/views/endings/index.html.erb
<h1>Listing all endings</h1>
<table class="table table-striped">
  <tr>
    <th>What Beginning</th>
    <th>Ending User</th>
    <th>Created</th>
    <th>Controls</th>
  </tr>

<% @endings.each do |ending| %>
  <tr>
    <td><%= ending.beginning.title %></td>
    <td><%= ending.user.name %></td>
    <td><%= time_ago_in_words(ending.created_at) %> ago</td>

      <td><%= link_to 'Show', ending, :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_ending_path(ending), :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Destroy', ending, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
    </div>
  </tr>
<% end %>
</table>

<br />

app/views/endings/new.html.erb
<h1>New ending</h1>

<%= render 'form' %>
<div class="form-actions">
<%= link_to 'Back', endings_path %>
</div>

app/views/endings/praise.js.erb
$("#praiseform").html("<%= escape_javascript(render('endings/unpraise')) %>")
$("#praised").html('<%= pluralize(@ending.votes_for, ' time') %>')

app/views/endings/show.html.erb
<div class ="alert alert-success">
<p>
  <b>For Beginning:</b>
  <%= @ending.beginning.title %>
</p>
<p>
  <b>Beginning Content:</b>
  <%= simple_format (@ending.beginning.content) %>
</p>
</div>
<div class ="alert alert-info"
<p>
<%= simple_format (@ending.content) %>
</p>
<p>
<b>Ending Title:</b>
<%= @ending.title %>
</p>
<p>
<b>Ending Created by lucid user:</b>
<%= @ending.user.name %> on  <%= @ending.created_at %>
</p>
<p>
<b>Ending has been praised <strong id="praised" class="stat">
<%= pluralize(@ending.votes_for, ' time') %></strong>.</b>
</p>
<p>
<b>Ending has been bookmarked <strong id="bookmarked" class="stat">
<%= pluralize(@ending.followers_count, ' time') %></strong>.</b>
</p>
<br />
<div class="row">
<div class="span2">
<div id="bookmarkform">
<% if @ending.followed_by?(current_user) %>
<%= render 'unbookmark' %>
<% else %>
<%= render 'bookmark' %>
<% end %>
</div>
</div>
<div class="span3">
<div id="praiseform">
<% if @ending.voted_by?(current_user) %>
<%= render 'unpraise' %>
<% else %>
<%= render 'praise' %>
<% end %>
</div>
</div>
</div>
</div>

<div class="form-actions">
<%= link_to 'Edit Ending', edit_ending_path(@ending), :class => 'btn btn-primary' %>
<%= link_to 'Back', endings_path, :class => 'btn btn-primary' %>
<br />
<br />

<div id="publishform">
<% if @ending.private? %>
<%= render 'publish' %>
<% else %>
<%= render 'unpublish' %>
<% end %>
</div>
</div>
<br />

<!--
<h2>Praise system</h2>
  <b>Ending has been praised <strong id="praised" class="stat">
 <%= pluralize(@ending.votes_for, ' time') %></strong>.</b>
<div id="voteform">
<p>
<% if @ending.voted_by?(current_user) %>
<%= render 'unpraise' %>
<% else %>
<%= render 'praise' %>
<% end %>
</p>
</div>
-->
<!--
<h2>Bookmark system</h2>
  <b>Ending has been bookmarked <strong id="bookmark" class="bm-stat">
 <%= pluralize(@ending.followers_count, ' time') %></strong>.</b>
</p>
<div id="bookmarkform">
<p>
<% if @ending.followed_by?(current_user) %>
<%= render 'unbookmark' %>
<% else %>
<%= render 'bookmark' %>
<% end %>
</p>
</div>
-->
<div id="comments">
<h2>Commenting system</h2>
  <%= nested_comments @ending.comments.includes(:user).arrange(:order => "created_at asc") %>
</div>
<div id="comment-form" >
  <%= render "comments/form" %>
</div>

app/views/endings/unbookmark.js.erb
$("#bookmarkform").html("<%= escape_javascript(render('endings/bookmark')) %>")
$("#bookmarked").html('<%= pluralize(@ending.followers_count, ' time') %>')

app/views/endings/unpraise.js.erb
$("#praiseform").html("<%= escape_javascript(render('endings/praise')) %>")
$("#praised").html('<%= pluralize(@ending.votes_for, ' time') %>')

app/views/endings/unpublish.js.erb
$("#publishform").html("<%= escape_javascript(render('endings/publish')) %>")