config/routes.rb
Lucidword::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    member do
      post :follow
      post :unfollow
    end
  end


  resources :beginnings do
    member do
      post :bookmark
      post :unbookmark
    end
  end
 
  resources :endings do
    member do 
      post :praise
      post :unpraise
      post :bookmark
      post :unbookmark
      post :publish
      post :unpublish
    end
  end

  resources :comments

end

app/models/beginning.rb
class Beginning < ActiveRecord::Base
  attr_accessible :content, :original_author, :title, :style_type, :embed_code

  acts_as_followable

  belongs_to :user
  has_many :endings

  validates :content, presence: true
  validates :title, presence: true
  validates :user_id, presence: true

  default_scope order: 'beginnings.created_at DESC'

end

app/controllers/beginnings_controller.rb
class BeginningsController < ApplicationController
  include ActionView::Helpers::TextHelper

  before_filter :authenticate_user!
 
  def  bookmark
    begin
      current_user.follow(@beginning = Beginning.find(params[:id]))

      respond_to do |format|
        format.html { redirect_to current_user, notice: 'You have bookmarked this beginning' }
        format.js
      end
    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
  end

  def unbookmark
    begin
      current_user.stop_following(@beginning = Beginning.find(params[:id]))

      respond_to do |format|
        format.html { redirect_to current_user, notice: 'You have removed your bookmark' }
         format.js
       end

    rescue ActiveRecord::RecordInvalid
      render :nothing => true, :status => 404
    end
 end

  # GET /beginnings
  # GET /beginnings.json

  def index
    @beginnings = Beginning.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beginnings }
    end
  end

  # GET /beginnings/1
  # GET /beginnings/1.json
  def show
    @ending = Ending.new
    @beginning = Beginning.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beginning }
    end
  end

  # GET /beginnings/new
  # GET /beginnings/new.json
  def new
    @beginning = Beginning.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beginning }
    end
  end

  # GET /beginnings/1/edit
  def edit
    @beginning = Beginning.find(params[:id])
  end

  # POST /beginnings
  # POST /beginnings.json
  def create
    @user = current_user
    @beginning = @user.beginnings.new(params[:beginning])

    respond_to do |format|
      if @beginning.save
        format.html { redirect_to @beginning, notice: 'Beginning was successfully created.' }
        format.json { render json: @beginning, status: :created, location: @beginning }
      else
        format.html { render action: "new" }
        format.json { render json: @beginning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beginnings/1
  # PUT /beginnings/1.json
  def update
    @beginning = Beginning.find(params[:id])

    respond_to do |format|
      if @beginning.update_attributes(params[:beginning])
        format.html { redirect_to @beginning, notice: 'Beginning was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beginning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beginnings/1
  # DELETE /beginnings/1.json
  def destroy
    @beginning = Beginning.find(params[:id])
    @beginning.destroy

    respond_to do |format|
      format.html { redirect_to beginnings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beginnings_helper.rb
module BeginningsHelper
end

app/views/beginnings/_bookmark.html.erb
<div class="bm-form">
<%= link_to 'Bookmark this beginning!', bookmark_beginning_path(@beginning), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/beginnings/_form.html.erb
<%= simple_form_for(@beginning) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, :input_html => { :class => "span4" } %>
    <%= f.input :original_author, :input_html => { :class => "span4" } %>
    <%= f.input :style_type, :collection => [ "Poetry", "Short Story", "Classic Novel"] %>
    <%= f.input :content, :as => :text, :input_html => { :class => "span6" }  %>


  </div>
   <div class="form-actions">
     <%= f.button :submit, :class => 'btn btn-primary' %>
   </div>
<% end %>

app/views/beginnings/_unbookmark.html.erb
<div class="bm-form">
<%= link_to 'Remove bookmark', unbookmark_beginning_path(@beginning), :method => :post, :class => 'btn btn-primary', remote: true %>
</div>

app/views/beginnings/bookmark.js.erb
$("#bookmarkform").html("<%= escape_javascript(render('beginnings/unbookmark')) %>")
$("#bookmark").html('<%= pluralize(@beginning.followers_count, ' time') %>')

app/views/beginnings/edit.html.erb
<h1>Editing beginning</h1>

<%= render 'form' %>
 <div class="form-actions">
<%= link_to 'Show', @beginning, :class => 'btn btn-primary' %>
<%= link_to 'Back', beginnings_path, :class => 'btn btn-primary' %>
</div>

app/views/beginnings/index.html.erb
<h1>Listing all beginnings</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Original Author</th>
    <th>Style</th>
    <th>Created</th>
    <th>Controls</th>
  </tr>

<% @beginnings.each do |beginning| %>
  <tr>
    <td><%= beginning.title %></td>
    <td><%= beginning.original_author %></td>
    <td><%= beginning.style_type %></td>
    <td><%= time_ago_in_words(beginning.created_at) %> ago</td>
      <td><%= link_to 'Show', beginning, :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_beginning_path(beginning), :class => 'btn btn-primary' %></td>
      <td><%= link_to 'Destroy', beginning, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary' %></td>
    </div>
  </tr>
<% end %>
</table>

<br />
 <div class="form-actions">
<%= link_to 'New Beginning', new_beginning_path, :class => 'btn btn-primary' %>
</div>

app/views/beginnings/new.html.erb
<h1>New beginning</h1>

<%= render 'form' %>
<div class="form-actions">
<%= link_to 'Back', beginnings_path, :class => 'btn btn-primary' %>
</div>

app/views/beginnings/show.html.erb
<div class ="alert alert-success">
<div id="bookmarkform">
<% if @beginning.followed_by?(current_user) %>
<%= render 'unbookmark' %>
<% else %>
<%= render 'bookmark' %>
<% end %>
</div>
<br />
<p>
  <b>Title:</b>
  <%= @beginning.title %>
</p>

<p>
  <b>Original Author:</b>
  <%= @beginning.original_author %>
</p>
<p>
  <b>Style:</b>
  <%= @beginning.style_type %>
</p>

<p> 
  <b>Created by lucid user:</b>
  <%= @beginning.user.name %> on  <%= @beginning.created_at %>
</p>

<p>
  <b>Content:</b>
  <%= simple_format (@beginning.content) %>
</p>
</div>
<div class="form-inputs">
<%= simple_form_for(@ending) do |f| %>
  <%= f.error_notification %>

  <%= f.input :content, :placeholder => 'dont be shy, finish this piece...', :label => false, :as => :text, :input_html => { :class => "span6" }  %>
  </div>
<%= f.hidden_field :beginning_id, :value => @beginning.id %>
<p>
  <b>A title for your ending?</b>
  <%= f.input :title, :label => false, :input_html => { :class => "span4" } %>
</p>


  <div class="form-actions">
    <%= f.button :submit, 'Save Ending', :class => 'btn btn-primary' %>
  </div>
<% end %>
<!--
<h2>Bookmark system</h2>
  <b>Beginning has been bookmarked <strong id="bookmark" class="bm-stat">
 <%= pluralize(@beginning.followers_count, ' time') %></strong>.</b>
</p>
<div id="bookmarkform">
<p>
<% if @beginning.followed_by?(current_user) %>
<%= render 'unbookmark' %>
<% else %>
<%= render 'bookmark' %>
<% end %>
</p>
</div>
-->

app/views/beginnings/unbookmark.js.erb
$("#bookmarkform").html("<%= escape_javascript(render('beginnings/bookmark')) %>")
$("#bookmark").html('<%= pluralize(@beginning.followers_count, ' time') %>')