config/routes.rb
Lucidword::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"

  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users, :only => [:show, :index] do
    member do
      post :follow
      post :unfollow
    end
  end


  resources :beginnings do
    member do
      post :bookmark
      post :unbookmark
    end
  end
 
  resources :endings do
    member do 
      post :praise
      post :unpraise
      post :bookmark
      post :unbookmark
      post :publish
      post :unpublish
    end
  end

  resources :comments

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag('Lucid1.png', :size => "80x20", :alt => "Lucid Word"), root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Beginnings', beginnings_path %>
    </li>
    <li>
    <%= link_to 'Endings', endings_path %>
    </li>
    <li>
    <%= link_to 'User List', users_path %>
    </li>
    <li>
    <%= link_to 'My Profile', user_path(current_user) %>
    </li>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %> 
    </li>

    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', rails_admin_path %>
      </li>
    <% end %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
   <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lucidword" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-inverse navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>